# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(max_length=255)),
                ('passcode', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='plus_one',
        ),
        migrations.AddField(
            model_name='invite',
            name='guest_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_1', to='form.Guest'),
        ),
        migrations.AddField(
            model_name='invite',
            name='guest_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_2', to='form.Guest'),
        ),
    ]
