# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_invite_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='form_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
