# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_invite_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
