# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_invite_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='guest_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites_2', to='form.Guest'),
        ),
    ]
