# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20171105_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='rsvp',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
